import Link from 'next/link';
import {notFound} from 'next/navigation';
import {getComparisonReport} from '@/lib/comparison-report';
import {isUuid} from '@/lib/uuid';
import {CLASSIFICATION_LABELS} from '@/lib/analysis-contract';
const classificationLabel=(value:unknown,fallback:string)=>typeof value==='string'?(CLASSIFICATION_LABELS[value as keyof typeof CLASSIFICATION_LABELS]??value):fallback;
export default async function Comparison({params}:{params:Promise<{id:string}>}){
 const {id}=await params;if(!isUuid(id))notFound();const report=await getComparisonReport(id);if(!report)notFound();
 return <main className="mx-auto max-w-6xl space-y-5 p-5"><Link className="underline" href={`/batches/${id}/results`}>Resultats del lot</Link><h1 className="text-2xl font-semibold">Comparació del lot {report.run.batch_number}</h1><Link className="underline" href={`/batches/${report.run.comparison_of}/results`}>Consultar lot origen</Link><p>{report.total} registres · {report.classificationChanges} canvis de classificació · {report.codeChanges} canvis de codi · {report.pendingHumanReview} revisions pendents</p><p>Les propostes automàtiques no substitueixen les decisions humanes anteriors. Dades no registrades: no disponibles; mai equivalents a zero.</p><a className="underline" href={`/api/batches/${id}/comparison`}>Descarregar informe JSON complet</a>{report.records.map(r=><article key={r.recordId} className="space-y-2 rounded border p-4"><h2 className="break-all font-semibold">{r.recordId}</h2><p>Automàtica: {classificationLabel(r.origin.classification,'No disponible')} → {classificationLabel(r.current.classification,'Pendent')}</p><p>Decisió humana anterior: {classificationLabel(r.origin.humanClassification,'Pendent')} · Revisió nova: {r.humanReviewPending?'Pendent':'Revisat'}</p><p>Durada: {r.origin.durationSeconds??'No disponible'} → {r.current.durationSeconds??'No disponible'} · Cost: no disponible</p><Link className="underline" href={`/review?state=all&batch=${id}&record=${r.recordId}&job=${r.jobId}`}>Revisar treball nou</Link><details><summary>Evidència, documents, codis, fases i ús disponible</summary><pre className="overflow-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify({origin:r.origin,current:r.current},null,2)}</pre></details></article>)}</main>;
}
