"use client";
import { AutoFilterForm } from "@/components/auto-filter-form";
import Link from "next/link";
import type { EntityFilters, EntityPage } from "@/lib/entity-types";
import { WorkPager, WorkTable } from "@/components/work-list";

export function EntitiesWorkbench({ result, filters }: { result: EntityPage; filters: EntityFilters }) {
  const origin = `/entities?${new URLSearchParams({ q: filters.query, qualification: filters.qualification, county: filters.county, page: String(result.page) })}`;
  return <main className="page-shell"><section className="page-container space-y-5">
    <div><p className="page-eyebrow">Referència · directori relacional</p><h1 className="page-title">Entitats</h1><p className="page-description">RESES acredita titularitat i tipologia; les provisions confirmades acrediten relacions amb la Cartera.</p></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-5">{[["Entitats", result.metrics.total], ["Serveis RESES", result.metrics.withReses], ["Registres vinculats", result.metrics.linkedRecords], ["Provisions confirmades", result.metrics.confirmed], ["Mencions pendents", result.metrics.pendingMentions]].map(([label, value]) => <div key={label} className="surface p-4"><strong className="text-xl">{value}</strong><p className="text-sm text-muted-foreground">{label}</p></div>)}</div>
    <AutoFilterForm className="surface grid gap-3 p-4 md:grid-cols-[minmax(0,1fr)_220px_220px_auto]"><input className="form-text" name="q" aria-label="Cercar entitat" placeholder="Nom legal o NIF…" defaultValue={filters.query}/><select className="form-control !h-10" name="qualification" aria-label="Qualificació" defaultValue={filters.qualification}><option value="totes">Totes les qualificacions</option>{result.qualifications.map(value => <option key={value}>{value}</option>)}</select><select className="form-control !h-10" name="county" aria-label="Comarca" defaultValue={filters.county}><option value="totes">Totes les comarques</option>{result.counties.map(value => <option key={value}>{value}</option>)}</select><button className="rounded-md bg-primary px-4 text-sm text-primary-foreground">Filtrar</button>{(filters.query || filters.qualification !== "totes" || filters.county !== "totes") && <Link className="text-sm underline" href="/entities">Netejar filtres</Link>}</AutoFilterForm>
    <WorkTable headings={["Entitat", "NIF", "Serveis RESES", "Provisions", "Validació", "Acció"]} empty={result.entities.length ? undefined : "No hi ha entitats amb aquests filtres."}>{result.entities.map(entity => { const href = `/entities/${entity.id}?${new URLSearchParams({ from: origin })}`; return <tr key={entity.id}><td data-label="Entitat"><Link className="font-semibold underline underline-offset-2" href={href}>{entity.legalName}</Link></td><td data-label="NIF">{entity.nif ?? "—"}</td><td data-label="Serveis RESES">{entity.services.length}</td><td data-label="Provisions">{entity.provisions}</td><td data-label="Validació">{entity.validationStatus}</td><td data-label="Acció"><Link className="inline-block rounded-md border px-3 py-2 text-sm" href={href}>Veure entitat</Link></td></tr>; })}</WorkTable>
    <WorkPager href={page => `/entities?${new URLSearchParams({ q: filters.query, qualification: filters.qualification, county: filters.county, page: String(page) })}`} page={result.page} pageCount={result.pageCount} total={result.total}/>
  </section></main>;
}
