"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { StableAccordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { Button, buttonVariants } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { FINANCING_TYPES, FINANCING_TYPE_LABELS } from "@/lib/financing-types";
import type { ApprovedFilters, ApprovedPage } from "@/lib/approved-types";
import { cn } from "@/lib/utils";
import { displaySourceIdentifier } from "@/lib/source-identifiers";

const STORAGE_KEY = "mapeig-approved-selection";
export function ApprovedWorkbench({ result, filters }: { result: ApprovedPage; filters: ApprovedFilters }) {
  const [selected, setSelected] = useState<string[]>([]); const [exporting, setExporting] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { const timer = window.setTimeout(() => { try { setSelected(JSON.parse(sessionStorage.getItem(STORAGE_KEY) ?? "[]")); } catch { setSelected([]); } }, 0); return () => window.clearTimeout(timer); }, []);
  function save(next: string[]) { setSelected(next); sessionStorage.setItem(STORAGE_KEY, JSON.stringify(next)); }
  const visible = result.provisions.map((item) => item.id); const allVisible = visible.length > 0 && visible.every((id) => selected.includes(id)); const allSelected = result.allProvisionIds.length > 0 && result.allProvisionIds.every((id) => selected.includes(id));
  async function exportSelected() { setExporting(true); setMessage(""); try { const response = await fetch("/api/exports/approved", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provisionIds: selected }) }); if (!response.ok) { const body = await response.json(); throw new Error(body.error ?? "No s'ha pogut generar l'Excel."); } const blob = await response.blob(); const disposition = response.headers.get("Content-Disposition") ?? ""; const filename = disposition.match(/filename="([^"]+)"/)?.[1] ?? "Detalle-Provisiones-Aprovats.xlsx"; const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); save([]); setMessage("Excel generat correctament."); } catch (error) { setMessage(error instanceof Error ? error.message : "Error d'exportació."); } finally { setExporting(false); } }
  const href = (page: number) => `/approved?${new URLSearchParams({ page: String(page), q: filters.query, batch: filters.batch, type: filters.type, service: filters.service })}`;
  return <main className="page-shell"><section className="page-container"><Badge variant="outline">Validació humana</Badge><div className="mt-3 flex items-center gap-2"><h1 className="text-2xl font-semibold">Aprovats</h1><Badge className="rounded-full px-2.5 tabular-nums">{result.total}</Badge></div><p className="mt-1 text-sm text-muted-foreground">Selecciona provisions vigents de qualsevol lot i exporta únicament les marcades.</p>
    <section className="surface mt-6 overflow-hidden"><form className="grid gap-3 border-b bg-muted/30 p-4 md:grid-cols-2 xl:grid-cols-[1fr_160px_200px_240px_auto]"><Input name="q" defaultValue={filters.query} placeholder="Entitat, NIF, registre o codi..."/><select className="form-control" name="batch" defaultValue={filters.batch}><option value="tots">Tots els lots</option>{result.batches.map((x) => <option key={x.id} value={x.id}>Lot {x.number}</option>)}</select><select className="form-control" name="type" defaultValue={filters.type}><option value="totes">Totes les tipologies</option>{FINANCING_TYPES.map((x) => <option key={x} value={x}>{FINANCING_TYPE_LABELS[x]}</option>)}</select><select className="form-control" name="service" defaultValue={filters.service}><option value="tots">Tots els serveis</option>{result.services.map((x) => <option key={x.code} value={x.code}>{x.code} · {x.name}</option>)}</select><Button variant="outline">Filtrar</Button></form>
      <div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => save(allVisible ? selected.filter((id) => !visible.includes(id)) : [...new Set([...selected, ...visible])])}>{allVisible ? "Desmarcar visibles" : "Seleccionar visibles"}</Button><Button variant="outline" size="sm" onClick={() => save(allSelected ? selected.filter((id) => !result.allProvisionIds.includes(id)) : [...new Set([...selected, ...result.allProvisionIds])])}>{allSelected ? "Desmarcar tots" : `Seleccionar tots (${result.total})`}</Button><Button variant="ghost" size="sm" onClick={() => save([])}>Netejar selecció</Button></div><div className="flex items-center gap-3"><span className="text-sm font-medium">{selected.length} seleccionats</span><Button size="sm" disabled={!selected.length || exporting} onClick={exportSelected}>{exporting ? "Generant..." : "Exportar seleccionats"}</Button></div></div>
      {message && <p className="border-b bg-muted/30 p-3 text-sm">{message}</p>}
      {result.provisions.length ? <StableAccordion stateKey="approved-provisions" className="divide-y">{result.provisions.map((item) => <AccordionItem key={item.id} value={item.id} className="px-4"><div className="flex items-center gap-3"><input type="checkbox" className="size-4 shrink-0 accent-black" aria-label={`Seleccionar ${displaySourceIdentifier(item.sourceId)}`} checked={selected.includes(item.id)} onChange={(event) => save(event.target.checked ? [...new Set([...selected, item.id])] : selected.filter((id) => id !== item.id))}/><AccordionTrigger className="min-w-0 gap-3 py-4 hover:no-underline"><div className="min-w-0 flex-1 text-left"><div className="flex flex-wrap items-start gap-2"><strong className="line-clamp-2 min-w-0 text-sm leading-5">{item.serviceCode} · {item.serviceName}</strong><Badge variant="secondary" className="shrink-0">{item.decision === "corrected" ? "Corregit" : "Aprovat"}</Badge></div><p className="mt-1 line-clamp-2 break-words text-xs leading-5 text-muted-foreground">Lot {item.batchNumber ?? "—"} · {item.providerName ?? "Entitat no informada"} · {displaySourceIdentifier(item.sourceId)}</p></div></AccordionTrigger></div><AccordionContent className="border-t pb-4 pt-3"><dl className="grid gap-3 text-sm sm:grid-cols-2"><Field label="Registre" value={item.title}/><Field label="Tipologia" value={FINANCING_TYPE_LABELS[item.financingType as keyof typeof FINANCING_TYPE_LABELS] ?? item.financingType}/><Field label="NIF" value={item.providerNif ?? "—"}/><Field label="Mecanisme" value={item.mechanism}/><Field label="Import" value={item.amount == null ? "—" : new Intl.NumberFormat("ca-ES", { style: "currency", currency: "EUR" }).format(item.amount)}/><Field label="Data" value={item.awardDate ?? "—"}/><Field label="Òrgan" value={item.contractingBody ?? "—"}/><Field label="Població" value={item.targetPopulation ?? "—"}/><Field label="Traçabilitat" value={item.sourceReference}/></dl></AccordionContent></AccordionItem>)}</StableAccordion> : <p className="p-8 text-center text-sm text-muted-foreground">No hi ha provisions aprovades amb aquests filtres.</p>}
      <div className="flex items-center justify-between border-t p-4 text-sm"><span>{result.total} provisions</span><div className="flex items-center gap-2"><Link href={href(Math.max(1,result.page-1))} className={cn(buttonVariants({variant:"outline"}),result.page<=1&&"pointer-events-none opacity-40")}>Anterior</Link><span>{result.page} / {result.pageCount}</span><Link href={href(Math.min(result.pageCount,result.page+1))} className={cn(buttonVariants({variant:"outline"}),result.page>=result.pageCount&&"pointer-events-none opacity-40")}>Següent</Link></div></div>
    </section></section></main>;
}
function Field({label,value}:{label:string;value:string}) { return <div><dt className="text-xs font-semibold text-muted-foreground">{label}</dt><dd className="mt-1 break-words">{value}</dd></div> }
