'use client';
import {useState,useRef} from 'react';
import Link from 'next/link';
type Preflight={token:string;batchNumber:number;provider:string;model:string;count:number;estimatedCost:number|null;estimatedSeconds:number|null;members:Array<{recordId:string;externalId:string;active:boolean;reusableDocuments:number;rediscover:boolean;documents?:Array<{id:string;url:string;hash:string|null;status:string;chunks:number}>}>};
export function BatchRerun({id}:{id:string}){
 const [preflight,setPreflight]=useState<Preflight|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[created,setCreated]=useState<{runId:string;dispatch:string}|null>(null),[confirmed,setConfirmed]=useState(false);
 const key=useRef('');
 async function inspect(){setBusy(true);setError('');try{const response=await fetch(`/api/batches/${id}/rerun`);const data=await response.json();if(!response.ok)throw Error(data.error);setPreflight(data);setConfirmed(false);key.current=crypto.randomUUID();}catch(e){setError(e instanceof Error?e.message:'No es pot llegir el preflight.');}finally{setBusy(false);}}
 async function create(){if(!preflight||!confirmed)return;setBusy(true);setError('');try{const response=await fetch(`/api/batches/${id}/rerun`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:preflight.token,idempotencyKey:key.current,confirmed:true})});const data=await response.json();if(!response.ok)throw Error(data.error);setCreated(data);}catch(e){setError(e instanceof Error?e.message:'Resposta desconeguda. Reintenta la mateixa confirmació per recuperar el lot, sense duplicar-lo.');}finally{setBusy(false);}}
 return <section className="space-y-3 rounded border p-4" aria-label="Reanàlisi comparativa"><h2 className="font-semibold">Reanalitzar com a lot nou</h2><p>Conserva el resultat anterior i no aprova provisions. Les operacions remotes requereixen autorització.</p>{created?<p role="status">Lot creat i identificat: <Link className="underline" href={`/batches/${created.runId}/comparison`}>{created.runId} · Veure comparació</Link>. Execució: {{queued:'En cua',completed:'Completada',started:'Iniciada',pending:'Despatx pendent'}[created.dispatch]??created.dispatch}.</p>:<><button className="rounded border px-3 py-2" disabled={busy} onClick={inspect}>Consultar preflight (només lectura)</button>{preflight&&<div className="space-y-3"><p>Lot origen {preflight.batchNumber} · {preflight.count} registres · Proveïdor {preflight.provider} · Model {preflight.model}</p><p>Cost estimat: {preflight.estimatedCost??'No disponible'} · Durada estimada: {preflight.estimatedSeconds??'No disponible'}</p><ul className="max-h-64 space-y-2 overflow-auto">{preflight.members.map(m=><li key={m.recordId} className="break-all">{m.externalId} · {m.recordId} · {m.reusableDocuments} documents reutilitzables · {m.rediscover?'Redescobriment pendent':'Resolució acreditada'}{m.active?' · BLOQUEJAT: treball actiu o resposta desconeguda':''}{m.documents&&<details><summary>Documents inclosos en la confirmació</summary><ul>{m.documents.map(d=><li key={d.id} className="mt-2 break-all text-xs">{d.url} · {d.chunks} fragments · Hash: {d.hash??'No disponible'}</li>)}</ul></details>}</li>)}</ul><label className="flex items-center gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Confirmo aquests {preflight.count} registres i la creació d’un lot nou.</label><button className="rounded bg-black px-3 py-2 text-white disabled:opacity-40" disabled={busy||!confirmed||!preflight.count||preflight.members.some(m=>m.active)} onClick={create}>Crear lot comparatiu confirmat</button></div>}</>}{error&&<p role="alert">{error}</p>}</section>;
}
