"use client";
import {useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {Dialog} from '@base-ui/react/dialog';
import {Button} from '@/components/ui/button';
export type SelectableDiscard={id:string;job_id:string;result_token:string;source_record_id:string;title:string};
export function DiscardedSelection({rows}:{rows:SelectableDiscard[]}){
 const [selected,setSelected]=useState<string[]>([]);const [open,setOpen]=useState(false);const [message,setMessage]=useState('');const [pending,start]=useTransition();const router=useRouter();
 const items=rows.filter(r=>selected.includes(r.id));
 function remove(){start(async()=>{try{const response=await fetch('/api/discarded/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({selection:items.map(({id,job_id,result_token})=>({id,job_id,result_token})),confirmedCount:items.length})});const result=await response.json();if(!response.ok)throw Error(result.error);setSelected([]);setOpen(false);setMessage(result.pending?'Registres eliminats; neteja de fitxers pendent.':'Eliminació completa; absència de fitxers verificada.');window.dispatchEvent(new Event('navigation-counts:refresh'));router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'No s’ha eliminat cap registre.');}});}
 return <section className="space-y-3 rounded-xl border p-4"><h2 className="font-semibold">Selecció per eliminar</h2><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={pending} onClick={()=>setSelected(rows.map(r=>r.id))}>Seleccionar visibles ({rows.length})</Button><Button variant="outline" disabled={pending} onClick={()=>setSelected([])}>Deseleccionar</Button><span className="p-2 text-sm">{items.length} seleccionats</span></div><ul className="space-y-2">{rows.map(r=><li key={r.id}><label className="flex items-start gap-3 text-sm"><input className="mt-1" type="checkbox" disabled={pending} checked={selected.includes(r.id)} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(id=>id!==r.id))}/><span>{r.source_record_id} · {r.title}</span></label></li>)}</ul><Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger render={<Button variant="outline" disabled={!items.length||pending}/>}>Eliminar seleccionats</Dialog.Trigger><Dialog.Portal><Dialog.Backdrop className="fixed inset-0 z-50 bg-black/30"/><Dialog.Popup className="fixed left-1/2 top-1/2 z-50 max-h-[90dvh] w-[min(95vw,45rem)] -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-xl border bg-background p-5"><Dialog.Title className="text-lg font-semibold">Eliminar definitivament {items.length} registres?</Dialog.Title><Dialog.Description className="my-3 text-sm">S’eliminaran registres, resultats, evidències i fitxers originals de l’aplicació. No es pot desfer. Els Excel descarregats fora de l’aplicació no s’eliminen.</Dialog.Description><ul className="space-y-2 text-sm">{items.map(r=><li key={r.id} className="rounded border p-2">{r.source_record_id}<br/><span className="break-all font-mono text-xs">{r.id}</span></li>)}</ul><div className="mt-4 flex flex-wrap gap-3"><Dialog.Close render={<Button variant="outline" disabled={pending}/>}>Cancel·lar</Dialog.Close><Button disabled={pending} onClick={remove}>{pending?'Verificant i eliminant...':`Confirmo l’eliminació de ${items.length}`}</Button></div>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}</Dialog.Popup></Dialog.Portal></Dialog.Root>{message&&<p role="status" className="text-sm">{message}</p>}</section>;
}
export function PurgePending({batches}:{batches:{id:string;record_count:number}[]}){
 const [pending,start]=useTransition();const [message,setMessage]=useState('');const router=useRouter();
 if(!batches.length)return null;
 return <section className="space-y-2 rounded border p-4"><h2 className="font-semibold">Registres eliminats; neteja de fitxers pendent</h2>{batches.map(batch=><div key={batch.id} className="flex flex-wrap items-center gap-3 text-sm"><span>{batch.record_count} registres · {batch.id}</span><Button variant="outline" disabled={pending} onClick={()=>start(async()=>{try{const r=await fetch(`/api/discarded/purge/${batch.id}`,{method:'POST'});const value=await r.json();setMessage(r.ok&&value.complete?'Neteja verificada.':'La neteja continua pendent.');router.refresh();}catch{setMessage('No s’ha pogut completar la neteja.');}})}>Reintentar neteja</Button></div>)}<p role="status">{message}</p></section>;
}
