import Link from 'next/link';
import {DiscardedSelection,PurgePending,type SelectableDiscard} from './discarded-selection';
import {createServerSupabase} from '@/lib/records-page';
import {getCurrentResults} from '@/lib/current-results';
import {DISCARD_REASON_LABELS} from '@/lib/review-contract';
import {FINANCING_TYPE_LABELS} from '@/lib/financing-types';
import {isUuid} from '@/lib/uuid';
export default async function DiscardedPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const params=await searchParams;const page=Math.max(1,parseInt(params.page??'1')||1);
 const filters={page,query:params.q?.slice(0,120),type:params.type,reason:params.reason,batch:params.batch&&isUuid(params.batch)?params.batch:undefined,destination:'discarded'};
 const result=await getCurrentResults(filters);
 const purges=await createServerSupabase().from('storage_purge_batches').select('id,record_count').is('completed_at',null).order('created_at',{ascending:false}).limit(100);if(purges.error)throw purges.error;
 function href(next:number){const q=new URLSearchParams();for(const [key,value]of Object.entries(params))if(value)q.set(key,value);q.set('page',String(next));return `?${q}`;}
 return <main className="mx-auto max-w-6xl space-y-5 p-5"><h1 className="text-2xl font-semibold">Descartats</h1><p className="text-sm text-muted-foreground">Un descart automàtic no és una validació humana. Pots revisar i rectificar cada cas.</p><form className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><input name="q" aria-label="Cerca" defaultValue={params.q} placeholder="Títol o identificador" className="form-control"/><select name="reason" aria-label="Motiu" defaultValue={params.reason??''} className="form-control"><option value="">Tots els motius</option>{Object.entries(DISCARD_REASON_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select name="type" aria-label="Tipologia" defaultValue={params.type??'totes'} className="form-control"><option value="totes">Totes les tipologies</option>{Object.entries(FINANCING_TYPE_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input name="batch" aria-label="UUID del lot" defaultValue={filters.batch} placeholder="UUID del lot" className="form-control"/><button className="rounded bg-black px-4 py-2 text-white">Filtrar</button></form><PurgePending batches={purges.data??[]}/><DiscardedSelection key={JSON.stringify(filters)} rows={result.rows as SelectableDiscard[]}/><p>{result.total} descartats · pàgina {page} de {result.pageCount}</p>{result.rows.map(row=><article key={row.id} className="space-y-2 rounded-xl border p-4"><h2 className="font-semibold">{row.title}</h2><p className="text-sm">{row.source_record_id} · {row.source_dataset} · {row.financing_type} · Lot {row.batch_number??'—'}</p><p className="text-sm">{row.human_reviewed?'Validat per una persona':'Pendent de validació humana'} · {row.job_created_at?new Date(row.job_created_at).toLocaleString('ca-ES'):'—'}</p><p>{(row.reasons as string[]|null)?.map(r=>DISCARD_REASON_LABELS[r]??r).join(', ')||'Motiu no registrat'}</p><p>{row.explanation}</p><details><summary>Evidència</summary>{(row.evidence as {content:string}[]|null)?.map((e,i)=><blockquote key={i} className="mt-2 border-l pl-3 text-sm">{e.content}</blockquote>)}</details><Link href={`/review?state=all&record=${row.id}`} className="inline-block underline">Revisar o rectificar</Link></article>)}<nav aria-label="Paginació" className="flex gap-4">{page>1&&<Link href={href(page-1)}>Anterior</Link>}{page<result.pageCount&&<Link href={href(page+1)}>Següent</Link>}</nav></main>;
}
